package com.blogapp.constants;

public enum Emessage {
	USERNAME_EXISTS,
	EMAIL_EXISTS,
	BLOG_NOT_FOUND,
	USER_NOT_FOUND,
	USER_REGISTERED,
	BLOG_POSTED,
	BLOG_UPDATED,
	BLOG_DELETED,
	COMMENT_ADDED,
	LIKE_ADDED,
	LIKE_REMOVED,
	CANNOT_UPDATE_BLOG,
	CANNOT_DELETE_BLOG
}
