#configure database
spring:
  servlet:
        multipart:
            file-size-threshold: 2KB
            max-file-size: 300MB
            max-request-size: 315MB
  data:
    mongodb:
      uri: mongodb+srv://admin:admin%40123@cluster0.885ps.mongodb.net/blogdb?retryWrites=true&w=majority
      database: blogdb
#      host: localhost
#      port: 27017
  datasource:
    url: jdbc:mysql://localhost:3306/mydb1?serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
server:
  port: 8087
pass:
  app:
    jwtSecret: varshaSecretKey
    jwtExpirationMs: 86400000
file:
    storage:
        location: fileStorage
## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
#file:
#    upload-dir: C:\Users\Varsha\Documents\GitHub\New folder2\blog-backend\uploads